Init gulp starter kit template, added data and data access layers
BuildFire/exampleWeatherPlugin pull request #1
Opened 2019-12-26 13:06 UTC by MiletaStanisic

*Note
Asana tickets does not exists

2019-12-27 13:33 UTC, denza commented on README.md
> +## merge
Please make sure to keep all changes from previous version.

2019-12-27 16:15 UTC, denza commented on control/content/samples/searchTable/dummyData.js
> +
Remove this file

2019-12-27 16:15 UTC, denza commented on control/content/samples/searchTable/searchTable.css
> +thead, tbody tr {
Remove this file

2019-12-27 16:15 UTC, denza commented on control/content/samples/searchTable/searchTable.html
> +<!DOCTYPE html>
Remove this file

2019-12-27 16:16 UTC, denza commented on control/content/samples/searchTable/searchTableConfig.js
> +
Remove this file

2019-12-27 16:16 UTC, denza commented on control/content/samples/searchTable/searchTableHelper.js
> +class SearchTableHelper{
Remove this file

2019-12-27 16:16 UTC, denza commented on control/content/samples/sortableList/sortableList.css
> +/* Draggable List  */
Remove this file

2019-12-27 16:16 UTC, denza commented on control/content/samples/sortableList/sortableList.html
> +<!DOCTYPE html>
Remove this file

2019-12-27 16:16 UTC, denza commented on control/content/samples/sortableList/sortableList.js
> +﻿
Remove this file

2019-12-27 16:16 UTC, denza commented on control/content/samples/sortableList/sortableListUI.js
> +const sortableListUI= {
Remove this file

2019-12-27 16:16 UTC, denza commented on control/content/samples/subPage/index.html
> +<!DOCTYPE html>
Remove this file

2019-12-27 16:16 UTC, denza commented on control/content/samples/subPage/subPage.css
> +.subPage{
Remove this file

2019-12-30 17:42 UTC, denza commented on control/content/index.html
> +    //location = "samples/sortableList/sortableList.html";
Please remove commented code

2019-12-30 17:45 UTC, denza reviewed
Looks good

2019-12-31 15:48 UTC, denza commented on tests/basic/settings.test.js
> +      return 4;
testCount should not be used if you have only one instance.

2020-01-06 16:13 UTC, denza commented on dataAccess/weatherData.js
> +    * Gets all barcodes
Barcodes?

2020-01-06 16:14 UTC, denza commented on dataAccess/weatherData.js
>          data.createdBy = authManager.currentUser.email;
Please use userId, not email address.

2020-01-06 16:15 UTC, denza commented on dataAccess/weatherData.js
> +            createdBy: authManager.currentUser.email
Please use userId, not email address.

2020-01-06 16:15 UTC, denza commented on dataAccess/weatherData.js
> +              lastUpdatedBy: authManager.currentUser.email
Please use userId, not email address.

2020-01-06 16:16 UTC, denza commented on tests/basic/weather.test.js
> +          console.log(data);
Remove log

2020-01-06 16:17 UTC, denza commented on tests/basic/weather.test.js
> +            console.error(err);
Remove log

2020-01-06 16:18 UTC, denza commented on tests/basic/weather.test.js
> +    }
We do not need this method

2020-01-13 19:06 UTC, najiatallah commented
Approved

2020-01-20 18:58 UTC, mikailbayram requested changes

2020-01-20 18:58 UTC, mikailbayram commented on widget/index.html
> +    fetch("https://api.openweathermap.org/data/2.5/find?appid=" + apiKey + "&lat=" + latitude + "&lon=" + longitude + tempUnit
lets move the endpoints to a higher level variable so that any change in the endpoint wont be "painful" on our side

2020-01-21 09:04 UTC, merged